#
# Makefile for the user netlink module used to communicate between user space and kernel space.
#

#add a line in ../Makefile
#obj-$(CONFIG_ACT_NL_KERNEL)	+= nl_kernel/

#obj-$(CONFIG_ACT_NL_KERNEL) += nl_kernel.o
obj-y += nl_kernel.o

#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
