/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 1
#define BCM_REL_RELEASE 1
#define BCM_REL_PATCH 10
#define BCM_SW_VERSIONCODE (1*65536+1*256+10)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
