dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_963268GW.save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_963268GW.save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f nvram_963268GW.save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_963268GW.save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_963268GW.save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_963268GW.save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlmngr_963268GW.save $(INSTALL_DIR)/bin/wlmngr
	cp -f wlevt_963268GW.save $(INSTALL_DIR)/bin/wlevt
	cp -f libwlmngr.so_963268GW.save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f libwlcsm.so_963268GW.save $(INSTALL_DIR)/lib/libwlcsm.so
	cp -f epi_ttcp_963268GW.save $(INSTALL_DIR)/bin/epi_ttcp
