<noscript><div style="color:red; font-size:20px;">Your browser does not support javascript!</div></noscript>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="pragma" content="no-cache">  
<meta http-equiv="Cache-Control" content="no-cache,must-revalidate"> 
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<link href="css/basic_20121119.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="js/jquery-2.1.1.min.js"></script>

<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript" src="js/mul_xml.js"></script>
<script type="text/javascript" src="js/access.js"></script>
<script type="text/javascript" src="js/include_inc.js"></script>
