 <div id="left_column">
	<div id="left_column_header"></div>
	<div id="left_column_content">
		<ul id="subnav">
			<li><a href="wl_network.html" class="link"><span id="left_wl_title" style='font-weight:bold;font-size:12px;'>Wireless Settings</span></a></li>
			<ul>
				<li><a href="wl_network.html" id="left_network" class="link"><span id="left_wl_net">Wireless Network List</span></a></li>
				<li><a href="wl_basic.html" id="left_basicsettings" class="link"><span id="left_wl_basic">Basic Setup</span></a></li>
				<li><a href="wl_security.html" id="left_security" class="link"><span id="left_wl_secur">Wireless Security</span></a></li>
	            <li><a href="wl_wfps.html" id="left_wps" class="link"><span id="left_wl_wps">WPS</span></a></li>
				<li><a href="wl_adv.html" id="left_advanced" class="link"><span id="left_wl_adv">Advanced Wireless Setup</span></a></li>
				<li><a href="wl_wac.html" id="left_wac" class="link"><span id="left_wl_control">Wireless Access Control</span></a></li>
				<li><a href="logout.cgi" id="left_logout" class="link" onClick=""><span id="left_wl_logout">Logout</span></a></li>
			</ul>
		</ul>
	</div>
	<div id="left_column_footer"></div>
</div>

