 <div id="left_column">
	<div id="left_column_header"></div>
	<div id="left_column_content">
		<ul id="subnav">
			<li><a href="moca_setup.html" class="link"><span id="left_moc_settings" style='font-weight:bold;font-size:12px;'>MoCA Settings</span></a></li>
			<ul>
				<li><a href="moca_setup.html" id="left_moca" class="link"><span id="left_moc_set">MoCA Coax Setup</span></a></li>

				<li><a href="logout.cgi" id="left_logout" class="link" onClick="javascript:logout();"><span id="left_moc_logout">Log out</span></a></li>

			</ul>
		</ul>
	</div>
	<div id="left_column_footer"></div>
</div>
