 <div id="left_column">
	<div id="left_column_header"></div>
	<div id="left_column_content">
		<ul id="subnav">
			<li><a href="adv_manage.html" class="link"><span id="lft_adv_set_title" style="font-weight:bold;font-size:12px;">Advanced Setup</span></a></li>
			<ul>
				<li><a href="adv_manage.html" id="left_manage" class="link"><span id="lft_adv_mng">Management</span></a></li>
				<li><a href="adv_password.html" id="left_password" class="link"><span id="lft_adv_chanpass">Change Password</span></a></li>
				<li><a href="adv_default.html" id="left_factory" class="link"><span id="lft_adv_default">Factory Default</span></a></li>

				<li><a href="adv_swap.html" id="left_restore" class="link"><span id="lft_adv_restore">Firmware Restore</span></a></li>


				<li><a href="adv_upgrade.html" id="left_upgrade" class="link"><span id="lft_adv_upgrade">Firmware Upgrade</span></a></li>

				<li><a href="adv_tr69.html" id="left_tr69" class="link"><span id="lft_tr69">TR-069</span></a></li>

				<li><a href="adv_localssh.html" id="left_localssh" class="link"><span id="lft_adv_ssh">Local SSH</span></a></li>


				
				<li><a href="adv_language.html" id="left_language" class="link"><span id="lft_adv_language">Language Settings</span></a></li>
				

				<li><a href="logout.cgi" id="left_logout" class="link" onClick="javascript:logout();"><span id="lft_adv_logout">Logout</span></a></li>

			</ul>
		</ul>
	</div>
	<div id="left_column_footer"></div>
</div>
