#export DIR_USERS=/home/frank/Project/WECB/rtl819x/users

all:
	make -C nanohttp
	make -C libcsoap
	make -C sockmsg
	make -C hnap
	make -C cisco

clean:  
	make -C nanohttp clean
	make -C libcsoap clean
	make -C sockmsg clean
	make -C hnap clean
	make -C cisco clean

