#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: libol-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags] [--static-libs] [--local-cflags] [--local-static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 0.3.18
      ;;
    --cflags)
      includes=-I${prefix}/include/libol
      echo $includes
      ;;
    --local-cflags)
      includes=-I`pwd`/libol-0.3.18/src
      echo $includes
      ;;
    --libs)
      libdirs=-L${exec_prefix}/lib
      echo $libdirs -lol -lnsl 
      ;;
    --static-libs)
      echo ${exec_prefix}/lib/libol.a -lnsl 
      ;;
    --local-static-libs)
      echo `pwd`/libol-0.3.18/src/.libs/libol.a -lnsl 

      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

